# Generated by Django 2.0 on 2021-03-22 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('limit', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=6)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Hard', 'Hard')], default='Easy', max_length=12)),
                ('publishDate', models.DateTimeField(auto_now_add=True, verbose_name='date time published')),
                ('position', models.IntegerField(default=1, verbose_name='Code')),
                ('column', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='column', to='kanban.Columns')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
