# Generated by Django 2.0 on 2021-03-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ('position',)},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='position',
            field=models.IntegerField(verbose_name='Code'),
        ),
    ]
