# Generated by Django 2.0 on 2021-03-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columns',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['column_id', 'position']},
        ),
        migrations.AlterField(
            model_name='columns',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
