# Generated by Django 2.0 on 2021-03-20 14:04

from django.db import migrations, models
import kanban.models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='position',
            field=models.IntegerField(default=kanban.models.ids, editable=False, unique=True, verbose_name='Code'),
        ),
    ]
