# Generated by Django 2.0 on 2021-03-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_auto_20210303_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='publishDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date time published'),
        ),
    ]
