# Generated by Django 2.0 on 2021-03-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_auto_20210320_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Code'),
        ),
    ]
