# Generated by Django 2.0 on 2021-03-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_auto_20210320_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ('position',)},
        ),
    ]
