# Generated by Django 2.0 on 2021-03-20 18:31

from django.db import migrations, models
import kanban.models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20210320_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='position',
            field=models.IntegerField(default=kanban.models.ids, unique=True, verbose_name='Code'),
        ),
    ]
