# Generated by Django 3.1.5 on 2021-04-14 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20210414_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='rows',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='row',
                to='kanban.rows'),
        ),
    ]
