# Generated by Django 2.0 on 2021-03-21 13:19

from django.db import migrations, models
import django.db.models.deletion
import kanban.models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20210320_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ('column_id', 'position')},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='column',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='column', to='kanban.Columns', validators=[kanban.models.validate_column_limit]),
        ),
    ]
