# Generated by Django 2.0 on 2021-03-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20210303_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('priority',)},
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
