# Generated by Django 3.1.5 on 2021-04-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_tasks_rows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rows',
            options={'ordering': ['id']},
        ),
    ]
