# Generated by Django 2.0 on 2021-03-20 18:32

from django.db import migrations, models
import kanban.models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_auto_20210320_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='position',
            field=models.IntegerField(default=kanban.models.ids, verbose_name='Code'),
        ),
    ]
