# Generated by Django 2.0 on 2021-03-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_auto_20210304_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columns',
            name='limit',
            field=models.IntegerField(default=999),
        ),
    ]
