# Generated by Django 2.0 on 2021-04-15 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_auto_20210415_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='row',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='row',
                to='kanban.Rows'),
        ),
    ]
