# Generated by Django 2.0 on 2021-04-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0008_auto_20210415_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Position'),
        ),
    ]
