# Generated by Django 3.1.7 on 2021-03-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0008_auto_20210304_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='column',
            new_name='columns',
        ),
    ]
