# Generated by Django 3.1.7 on 2021-03-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0009_auto_20210304_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='columns',
            new_name='column',
        ),
    ]
