# Generated by Django 3.1.7 on 2021-03-11 12:54

from django.db import migrations, models
import kanban.models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0010_auto_20210304_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='even_field',
            field=models.IntegerField(default=0, validators=[kanban.models.validate_column_limit]),
            preserve_default=False,
        ),
    ]
