# Generated by Django 3.1.7 on 2021-03-11 13:03

from django.db import migrations, models
import django.db.models.deletion
import kanban.models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0012_auto_20210311_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='even_field',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column', to='kanban.columns', validators=[kanban.models.validate_column_limit]),
        ),
    ]
