# Generated by Django 3.1.7 on 2021-03-11 13:57

from django.db import migrations, models
import django.db.models.deletion
import kanban.models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0013_auto_20210311_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='column', to='kanban.columns', validators=[kanban.models.validate_column_limit]),
        ),
    ]
