# Generated by Django 2.0 on 2021-04-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0013_auto_20210415_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cells',
            name='column',
        ),
        migrations.RemoveField(
            model_name='cells',
            name='row',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='cell',
        ),
        migrations.AddField(
            model_name='tasks',
            name='column',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='column', to='kanban.Columns'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='row',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='row', to='kanban.Rows'),
        ),
        migrations.DeleteModel(
            name='Cells',
        ),
    ]
