# Generated by Django 3.1.7 on 2021-03-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0014_auto_20210311_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columns',
            name='limit',
            field=models.IntegerField(null=True),
        ),
    ]
