# Generated by Django 3.1.7 on 2021-03-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0015_auto_20210315_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='publishDate',
            new_name='publish_date',
        ),
    ]
