# Generated by Django 3.1.5 on 2021-04-29 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0020_auto_20210429_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='User',
        ),
        migrations.AddField(
            model_name='tasks',
            name='User',
            field=models.ManyToManyField(null=True, related_name='danie', to=settings.AUTH_USER_MODEL),
        ),
    ]
