# Generated by Django 3.2 on 2021-04-29 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0021_auto_20210429_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='User',
            field=models.ManyToManyField(
                related_name='danie', to=settings.AUTH_USER_MODEL),
        ),
    ]
