# Generated by Django 3.2 on 2021-05-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0025_auto_20210429_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['columnId', 'rowId', 'position']},
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='User',
        ),
    ]
