# Generated by Django 3.2 on 2021-05-03 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0026_auto_20210503_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='User',
            field=models.ManyToManyField(related_name='danie', to=settings.AUTH_USER_MODEL),
        ),
    ]
